# netlify.toml (at repo root)
[build]
  base      = "server"
  command   = "npm install"
  publish   = "server"           # points at your project root under `server/`
  functions = "server/functions" # where api.js lives

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200
