# netlify.toml
[build]
  command   = "npm --prefix server install"    # Install deps in server/
  publish   = "server"                         # This just needs to point *somewhere*, won't be used for API
  functions = "server/functions"               # Correct relative path from root

[functions]
  external_node_modules = ["express", "serverless-http", "cors", "dotenv", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
