[build]
  base      = "."  
  # first cd into client, install deps, then build
  command   = "cd client && npm ci && npm run build"
  publish   = "client/build"

[functions]
  directory = "server/functions"
  external_node_modules = ["express","serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200
  force  = true
