# netlify.toml at the root of your monorepo

# This is the main build settings for your site (frontend)
[build]
  # This tells Netlify to change into your 'client/' directory
  # before running the 'command' and looking for the 'publish' directory.
  base = "client/"
  command = "npm run build" # Or "yarn build"
  publish = "build"  # This is relative to the 'base' directory (client/build)


# This section explicitly defines settings for Netlify Functions.
# The 'directory' path here is relative to the REPOSITORY ROOT.
[functions]
  directory = "server/functions" # CORRECTED: Path to functions, relative to repo root
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Optional: Configuration for Netlify Dev (local development using `netlify dev`)
[dev]
  command = "npm start --prefix client" # Or "yarn start --cwd client"
  port = 3000
  # The functions path here should also be relative to the REPOSITORY ROOT for local dev
  functions = "server/functions" 
  publish = "build" 
  framework = "#custom"
